[book]
authors = ["sinu.eth", "themighty1"]
language = "en"
multilingual = false
src = "src"
title = "tlsn-docs"

[output.html]
default-theme = "ayu"
additional-css = ["src/css/katex.css", "src/css/global.css"]
use-site-url-as-root = true
git-repository-url = "https://github.com/tlsnotary/docs-mdbook"
edit-url-template = "https://github.com/tlsnotary/docs-mdbook/edit/main/{path}"


[output.linkcheck]
# Ignore warnings because of the many false-postives in katex formulas
warning-policy = "ignore"

[preprocessor.katex]
after = ["links"]
